In [ ]:
import pandas as pd
import numpy as np
data=pd.read_csv(r"/content/sample_data/Final!!.csv")
data

PARAMETERS   SO2    CO    NO    NO2    NOX   NH3     O3  AQI    WS  \
0    01/01/2023  2.02  0.06  8.93  17.84  26.00  8.93  26.07   72  0.33   
1    02/01/2023  1.63  0.12  8.89  17.74  26.00  8.89  25.97   81  0.47   
2    03/01/2023  3.46  0.03  8.91  17.89  26.00  8.91  26.03   82  0.19   
3    04/01/2023  2.79  0.11  8.88  17.77  26.00  8.88  25.95   79  0.54   
4    05/01/2023  1.15  0.22  9.48  17.73  26.00  9.48  23.93   84  0.43   
..          ...   ...   ...   ...    ...    ...   ...    ...  ...   ...   
670  12/27/2024  3.53  0.53  1.45   5.34   6.68  1.45  36.20   66  0.80   
671  12/28/2024  3.65  0.48  1.44   5.35   6.72  1.44  36.17   64  0.82   
672  12/29/2024  4.64  0.49  1.42   5.35   6.58  1.42  36.21   60  0.82   
673  12/30/2024  4.18  0.53  1.44   5.37   6.77  1.44  36.20   60  0.70   
674  12/31/2024  3.67  0.62  1.42   5.35   6.61  1.42  36.19   60  0.72   

         WD     RH      SR     TC  
0     37.96  80.27  199.80  28.70  
1     33.84  82.50  189.10  28.11  
2     54.37  71.00  203.10  28.55  
3     40.44  78.11  205.20  28.25  
4     42.53  78.56  202.30  28.55  
..      ...    ...     ...    ...  
670  151.19  83.99   98.19  30.23  
671  159.29  76.87   95.05  29.99  
672  148.56  78.66  100.60  30.42  
673  143.66  86.57   98.00  30.22  
674  163.21  77.02   96.68  30.12  

[675 rows x 14 columns]

In [ ]:
data.shape

(675, 14)

In [ ]:
data.isnull().sum()

PARAMETERS    0
SO2           0
CO            0
NO            0
NO2           0
NOX           0
NH3           0
O3            0
AQI           0
WS            0
WD            0
RH            0
SR            1
TC            0
dtype: int64

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.isnull().sum()

PARAMETERS    0
SO2           0
CO            0
NO            0
NO2           0
NOX           0
NH3           0
O3            0
AQI           0
WS            0
WD            0
RH            0
SR            0
TC            0
dtype: int64

In [ ]:
data

PARAMETERS   SO2    CO    NO    NO2    NOX   NH3     O3  AQI    WS  \
0    01/01/2023  2.02  0.06  8.93  17.84  26.00  8.93  26.07   72  0.33   
1    02/01/2023  1.63  0.12  8.89  17.74  26.00  8.89  25.97   81  0.47   
2    03/01/2023  3.46  0.03  8.91  17.89  26.00  8.91  26.03   82  0.19   
3    04/01/2023  2.79  0.11  8.88  17.77  26.00  8.88  25.95   79  0.54   
4    05/01/2023  1.15  0.22  9.48  17.73  26.00  9.48  23.93   84  0.43   
..          ...   ...   ...   ...    ...    ...   ...    ...  ...   ...   
670  12/27/2024  3.53  0.53  1.45   5.34   6.68  1.45  36.20   66  0.80   
671  12/28/2024  3.65  0.48  1.44   5.35   6.72  1.44  36.17   64  0.82   
672  12/29/2024  4.64  0.49  1.42   5.35   6.58  1.42  36.21   60  0.82   
673  12/30/2024  4.18  0.53  1.44   5.37   6.77  1.44  36.20   60  0.70   
674  12/31/2024  3.67  0.62  1.42   5.35   6.61  1.42  36.19   60  0.72   

         WD     RH      SR     TC  
0     37.96  80.27  199.80  28.70  
1     33.84  82.50  189.10  28.11  
2     54.37  71.00  203.10  28.55  
3     40.44  78.11  205.20  28.25  
4     42.53  78.56  202.30  28.55  
..      ...    ...     ...    ...  
670  151.19  83.99   98.19  30.23  
671  159.29  76.87   95.05  29.99  
672  148.56  78.66  100.60  30.42  
673  143.66  86.57   98.00  30.22  
674  163.21  77.02   96.68  30.12  

[674 rows x 14 columns]

In [ ]:
data.columns

Index(['PARAMETERS', 'SO2', 'CO', 'NO', 'NO2', 'NOX', 'NH3', 'O3', 'AQI', 'WS',
       'WD', 'RH', 'SR', 'TC'],
      dtype='object')

In [ ]:
x=data[[ 'SO2', 'CO', 'NO', 'NO2', 'NOX', 'NH3', 'O3', 'WS',
       'WD', 'RH', 'SR', 'TC']]
y=data['AQI']


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train.shape

(539, 12)

In [ ]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)
y_pred=reg.predict(x_test)
y_pred

array([73.13801444, 64.81335925, 72.98055067, 57.89944413, 68.01884252,
       66.50714663, 59.68331179, 76.70065357, 62.0847467 , 59.69500734,
       42.01060752, 51.83338069, 66.90667952, 80.62102586, 71.51332429,
       35.09661018, 67.64462509, 73.16122672, 62.89609539, 60.33774431,
       56.00720747, 63.98494812, 61.94835646, 48.90165767, 51.32671083,
       56.61463559, 80.61655193, 67.06942834, 65.15889019, 48.2291888 ,
       89.70660629, 46.61272119, 60.99054147, 58.43903524, 59.27714487,
       62.86756474, 77.75491536, 39.707919  , 79.11264143, 70.18677517,
       73.17267579, 81.96812809, 67.98000267, 62.4178752 , 80.14357557,
       67.89455373, 76.0768921 , 61.83581611, 81.08821671, 63.68718516,
       60.37537989, 71.65326615, 94.19726033, 46.52928037, 76.42426489,
       50.083662  , 80.38320583, 60.72603987, 80.42475174, 47.18544896,
       60.49152542, 41.64766621, 60.12499902, 63.92740964, 60.26873715,
       41.79616132, 56.48378228, 63.8800059 , 75.54199794, 59.99

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6456122456013591

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
reg1=KNeighborsRegressor()
reg1.fit(x_train,y_train)
y_pred=reg1.predict(x_test)
y_pred

array([91. , 56. , 85.8, 57. , 65.4, 65.4, 59.8, 84.8, 61.2, 62.6, 46.2,
       61.4, 58.4, 70.4, 61.4, 50. , 60.4, 93.4, 53.8, 54.4, 57.6, 62.2,
       83.8, 43. , 61.2, 38. , 90.2, 60.6, 51. , 42. , 61. , 56. , 55. ,
       59. , 56. , 63. , 83.6, 36. , 71.2, 53.4, 52.8, 78. , 92.6, 65.6,
       78. , 52.4, 66.6, 56.6, 75.4, 59.6, 57.6, 59.4, 95.8, 46. , 85.2,
       55. , 63.6, 58. , 64.2, 39.8, 65.8, 35.8, 68.8, 57.8, 53.2, 48.6,
       56. , 59.8, 66.6, 55.4, 64. , 58. , 66.4, 83.6, 58.6, 52.6, 57.8,
       88. , 55.8, 62.4, 93. , 46.6, 86.8, 36.6, 40.2, 37. , 88.4, 67.4,
       57.8, 79. , 49.8, 58.6, 39.6, 49.8, 62.6, 63.6, 78. , 57.4, 64.8,
       41.8, 38. , 84.8, 52. , 92.2, 77.4, 58. , 59.8, 54.2, 55.2, 46.8,
       83.6, 86.2, 73.4, 40.8, 49.8, 53. , 62.4, 93.4, 75.2, 55.2, 89.4,
       81.8, 71.6, 86. , 42.2, 93.4, 89.2, 95. , 40.2, 56.8, 50. , 34.2,
       73.4, 85. , 49.6])

In [ ]:
r2_score(y_test,y_pred)

0.6670461444690612

In [ ]:
from sklearn.tree import DecisionTreeRegressor
reg3=DecisionTreeRegressor()
reg3.fit(x_train,y_train)
y_pred=reg3.predict(x_test)
y_pred

array([ 85.,  59.,  85.,  49.,  65.,  70.,  66.,  82.,  63.,  61.,  30.,
        48.,  67.,  79.,  60.,  54.,  58.,  86.,  78.,  47.,  43.,  62.,
        85.,  43.,  50.,  38.,  86.,  70.,  53.,  39.,  38.,  30.,  64.,
        58.,  58.,  59.,  83.,  41.,  99.,  66.,  85.,  83.,  78.,  63.,
        77.,  70.,  82.,  70.,  79.,  55.,  60.,  89.,  79.,  47.,  84.,
        47., 112.,  63.,  88.,  38.,  58.,  31.,  65.,  72.,  63.,  58.,
        58.,  63.,  70.,  59.,  53.,  51.,  46.,  70.,  71.,  89.,  50.,
        82.,  52.,  63.,  87.,  60.,  82.,  78.,  37.,  42.,  99.,  61.,
        50.,  44.,  29.,  62.,  43.,  56.,  60.,  63.,  83.,  57.,  67.,
        37.,  38.,  82.,  38.,  93.,  82.,  50.,  40.,  83.,  47.,  46.,
        86.,  86.,  88.,  47.,  60.,  50.,  68.,  98.,  64.,  70., 100.,
        84.,  78.,  83.,  41.,  98.,  83.,  87.,  34.,  51.,  40.,  47.,
        86.,  87.,  51.])

In [ ]:
r2_score(y_test,y_pred)

0.6477474762540418

In [ ]:
from sklearn.ensemble import RandomForestRegressor
reg4=RandomForestRegressor(n_estimators=100)
reg4.fit(x_train,y_train)
y_pred=reg4.predict(x_test)
y_pred

array([87.2 , 61.11, 85.07, 56.36, 66.11, 67.28, 64.11, 83.81, 62.27,
       60.09, 44.55, 55.79, 60.59, 86.43, 60.25, 49.01, 56.68, 88.51,
       66.97, 49.88, 55.07, 60.34, 72.56, 47.13, 52.89, 38.96, 88.96,
       67.36, 55.09, 44.9 , 51.15, 45.96, 60.11, 55.77, 57.73, 60.65,
       84.04, 35.93, 91.5 , 58.92, 67.33, 82.26, 74.17, 63.23, 79.13,
       55.92, 82.85, 57.41, 81.62, 59.54, 62.19, 86.17, 87.04, 46.17,
       84.72, 51.22, 86.08, 61.04, 80.53, 40.5 , 60.43, 35.22, 59.99,
       59.72, 57.63, 52.46, 57.69, 53.22, 72.9 , 59.85, 58.33, 54.31,
       63.98, 71.87, 63.08, 87.35, 57.  , 84.43, 55.52, 61.65, 90.45,
       48.34, 82.6 , 46.46, 41.36, 51.27, 91.76, 61.22, 53.36, 66.04,
       37.84, 62.88, 42.37, 55.48, 65.48, 63.06, 82.06, 58.01, 62.06,
       49.87, 38.48, 80.09, 44.43, 88.29, 80.53, 57.43, 58.18, 69.49,
       55.56, 51.2 , 89.29, 88.6 , 79.28, 48.3 , 56.13, 45.45, 64.01,
       93.79, 68.43, 52.63, 84.86, 82.62, 64.14, 83.49, 41.13, 93.21,
       84.06, 88.37,

In [ ]:
r2_score(y_test,y_pred)

0.8206544504836848

In [ ]:
import pickle
with open('model.pkl','wb') as file:
  pickle.dump(reg4,file)